# Generated by Django 4.2.7 on 2025-12-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='custom_properties',
            field=models.JSONField(blank=True, default=dict, help_text='Custom properties validated against letter_type.meta_schema'),
        ),
        migrations.AlterField(
            model_name='lettertype',
            name='meta_schema',
            field=models.JSONField(blank=True, default=dict, help_text='JSON schema defining the structure of custom properties'),
        ),
    ]
